dns: ''
server: 'media'
domain: 'honk'
dev_http_port: 8081
dev_https_port: 8443
use_https: false
allowedOrigins:
  - 'http://localhost:8080'
  - 'http://192.168.0.11'
# Paths for file directories containing media
# Should point to the parent directory of the media directories (see structure in README)
userMediaPaths:
  video: '/home/benjamyan/Working/media-server/media/video'
  audio: '/home/benjamyan/Working/media-server/media/audio'
  image: '/home/benjamyan/Working/media-server/media/image'
# Standard users to load into the DB -- "Username__Password"
users:
    - 'user__pass'
    - 'BigTony__G00seGame'
    - 'JoeyJabroni__doodoo'
# Admin credentials
admins:
    - 'mediahonk__pringle'
    